[package]
name = "aoc_2018"
version = "0.1.0"
authors = ["zoewithabang <zoewithabang@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
chrono = "0.4.7"
itertools = "0.8.0"
regex = "1.2.0"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "benchmark"
harness = false
